name: CI
on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Package & compile rascal-lsp
        working-directory: ./rascal-lsp
        run: mvn -B clean verify

      - name: Append build id if pre-release
        if: ${{ !startsWith(github.ref, 'refs/tags/rascal-lsp') }}
        working-directory: ./rascal-vscode-extension
        run: sed -i "s/\\(\"version\":.*\\)\\-head/\\1-head$GITHUB_RUN_NUMBER/" package.json

      - name: Package & compile extension 
        if: ${{ !startsWith(github.ref, 'refs/tags/rascal-lsp') }}
        working-directory: ./rascal-vscode-extension
        run: |
          npm ci
          npm run license-check
          npm run compile
          npm run lint 
          npm run normalTest
          # disable vs-code test npm run test

      - name: package extension
        if: ${{ !startsWith(github.ref, 'refs/tags/rascal-lsp') }}
        working-directory: rascal-vscode-extension
        run: |
          npm run lsp4j:package
          npx vsce package

      - name: upload final vsix 
        if: ${{ !startsWith(github.ref, 'refs/tags/rascal-lsp') }}
        uses: actions/upload-artifact@v2
        with:
          path: rascal-vscode-extension/*.vsix
          retention-days: 20

      - name: Publish release to Visual Studio Marketplace
        if: ${{ !startsWith(github.ref, 'refs/tags/rascal-lsp') }}
        if: startsWith(github.ref, 'refs/tags/v')
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          packagePath: ./rascal-vscode-extension
          pat: ${{ secrets.AZURE_USETHESOURCE_PAT }}
          registryUrl: https://marketplace.visualstudio.com

      - name: Attach rascal-lsp artifact
        if: ${{ startsWith(github.ref, 'refs/tags/rascal-lsp') }}
        id: build-artifact
        uses: SWAT-engineering/maven-full-artifacts-action@v1

      - name: Deploy rascal-lsp artifact
        working-directory: ./rascal-lsp
        if: startsWith(github.ref, 'refs/tags/rascal-lsp')
        uses: usethesource/releases-maven-action@v1
        with:
          maven-username: ${{ secrets.RELEASE_MAVEN_USERNAME }}
          maven-password: ${{ secrets.RELEASE_MAVEN_PASSWORD }}
          maven-local-port: ${{ secrets.RELEASE_MAVEN_LOCAL_PORT }}
          ssh-hostname: ${{ secrets.RELEASE_SSH_SERVER }}
          ssh-known-host: ${{ secrets.RELEASE_SSH_KNOWN_HOSTS }}
          ssh-username: ${{ secrets.RELEASE_SSH_USERNAME }}
          ssh-private-key: ${{ secrets.RELEASE_SSH_PRIVATE_KEY }}

