name: CI
on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Package & compile rascal-lsp
        working-directory: ./rascal-lsp
        run: mvn -B clean verify

      - name: Append build id if pre-release
        working-directory: ./rascal-vscode-extension
        run: sed -i "s/\\(\"version\":.*\\)\\-head/\\1-head$GITHUB_RUN_NUMBER/" package.json

      - name: Package & compile extension 
        working-directory: ./rascal-vscode-extension
        run: |
          npm ci
          npm run license-check
          npm run compile
          # npm run test

      - name: package extension
        working-directory: rascal-vscode-extension
        run: |
          npm run lsp4j:package
          npx vsce package

      - name: upload final vsix 
        uses: actions/upload-artifact@v2
        with:
          path: rascal-vscode-extension/*.vsix
          retention-days: 20

      - name: Publish release to Visual Studio Marketplace
        if: startsWith(github.ref, 'refs/tags/v')
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          packagePath: ./rascal-vscode-extension
          pat: ${{ secrets.AZURE_USETHESOURCE_PAT }}
          registryUrl: https://marketplace.visualstudio.com