name: Build and Deploy
on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: rascal-vscode-extension/package-lock.json

      - name: Package & compile rascal-lsp
        working-directory: ./rascal-lsp
        run: mvn -B clean verify

      - name: Commit-date
        id: commit-time
        run: echo "stamp=$(git log -1 --date=format:\"%Y%m%d%H%M\" --format=%cd)" >> $GITHUB_OUTPUT

      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          format: YYYYMMDDHHmm
          utcOffset: "00:00"

      - name: Append build id if pre-release
        working-directory: ./rascal-vscode-extension
        run: sed -i "s/\\(\"version\":.*\\)\.0\"/\\1.$stamp\"/" package.json
        env:
          stamp: "${{ steps.commit-time.outputs.stamp }}"

      - name: Package & compile extension 
        working-directory: ./rascal-vscode-extension
        run: |
          npm ci
          npm run license-check
          npm run compile
          npm run lint 
          npm run normalTest
          # disable vs-code test npm run test

      - name: package extension
        working-directory: rascal-vscode-extension
        run: |
          npm run lsp4j:package
          npx vsce package

      - name: Publish (pre-)release to Visual Studio Marketplace
        if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main'
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          packagePath: ./rascal-vscode-extension
          pat: ${{ secrets.AZURE_USETHESOURCE_PAT }}
          registryUrl: https://marketplace.visualstudio.com
          preRelease: ${{ github.ref == 'refs/heads/main' }}
