name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Package & compile rascal-lsp
        working-directory: ./rascal-lsp
        run: mvn -B --update-snapshots clean package

      - name: Package & compile extension 
        working-directory: ./rascal-vscode-extension
        run: |
          npm ci
          npm run compile
          npm run test

      - name: package extension
        working-directory: rascal-vscode-extension
        run: |
          npm run lsp4j:package
          npx vsce package

      - name: upload final vsix 
        uses: actions/upload-artifact@v2
        with:
          path: rascal-vscode-extension/*.vsix
          retention-days: 1